---

- name: Set up Docker
  hosts: all
  roles:
    - geerlingguy.docker
  become: yes

- name: Docker login
  tasks:
    - name: Login into Docker hub
      docker_login:
        username: dmi3papka
        password: "{{ docker_pat }}"

- name: Deploy app
  hosts: app
  roles:
    - app-deployment

- name: Deploy load balancer
  hosts: load_balancer
  roles:
    - load-balancer-deployment
