---
- name: Run application container
  docker_container:
    name: simple-app
    image: dmi3papka/simple-app:1.0.2
    ports:
      - "80:80"
    restart_policy: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1/ping"]
      interval: 1m30s
      timeout: 5s
      retries: 3