name: Deployment

on:
  workflow_dispatch:
    inputs:
      app_hosts:
        required: true
      load_balancer_host:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create inventory file
        run: |
          IFS=',' read -ra APP_HOSTS <<< "${{ inputs.app_hosts }}"
          cat <<EOF >> /tmp/inventory.yml
            all:
              vars:
                ansible_user: ansible
                ansible_ssh_private_key_file: /tmp/ansible_private_key
                ansible_python_interpreter: /usr/bin/python3
            app:
              hosts:
          EOF

          for host in "${APP_HOSTS[@]}"; do
            echo "      $host:" >> /tmp/inventory.yml
          done

          cat <<EOF >> /tmp/inventory.yml
            load_balancer:
              hosts:
                ${{ inputs.load_balancer_host }}:
          EOF

      - name: Generate Ansible private key
        run: |
          cat <<EOF >> /tmp/ansible_private_key
            ${{ secrets.ANSIBLE_PRIVATE_KEY }}
          EOF

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: main.yml
          vault_password: "${{ secrets.ANSIBLE_VAULT_PASSWORD }}"
          requirements: requirements.yml
          options: |
            --inventory /tmp/inventory.yml