name: Deployment

on:
  workflow_dispatch:
    inputs:
      app_hosts:
        required: true
      load_balancer_host:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create inventory file
        run: |
          IFS=',' read -ra APP_HOSTS <<< "${{ inputs.app_hosts }}"
          cat <<EOF >> /tmp/inventory.yml
            all:
              vars:
                ansible_user: ansible
                ansible_ssh_private_key_file: /tmp/ansible_private_key
                ansible_python_interpreter: /usr/bin/python3
            app:
              hosts:
          EOF

          for host in "${APP_HOSTS[@]}"; do
            echo "      $host:" >> /tmp/inventory.yml
          done

          cat <<EOF >> /tmp/inventory.yml
            load_balancer:
              hosts:
                ${{ inputs.load_balancer_host }}:
          EOF

      - name: Print inventory file
        run: cat /tmp/inventory.yml