name: Deployment

on:
  workflow_dispatch:
    inputs:
      app_hosts:
        required: true
      load_balancer_host:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create inventory file
        run: |
          APP_HOSTS=""
          IFS=',' read -ra APP_HOSTS_LIST <<< "${{ inputs.app_hosts }}"
          for host in "${APP_HOSTS_LIST[@]}"; do
            APP_HOSTS+="    $host:\n"
          done

          export APP_HOSTS

          envsubst < main-inventory.tpl > /tmp/inventory.yml

      - name: Print inventory file
        run: cat /tmp/inventory.yml