name: Deployment

on:
  workflow_dispatch:
    inputs:
      app_hosts:
        required: true
      load_balancer_host:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create inventory file
        run: |
          cat << EOF > /tmp/inventory.yml
          all:
            vars:
              ansible_user: ansible
              ansible_ssh_private_key_file: /tmp/ansible_private_key
              ansible_python_interpreter: /usr/bin/python3
          app:
            hosts:
          EOF

          IFS=',' read -ra APP_HOSTS <<< "${{ inputs.app_hosts }}"
          for host in "${APP_HOSTS[@]}"; do
            echo "  $host" >> inventory.yml
          done

          cat << EOF > /tmp/inventory.yml
          load_balancer:
            hosts:
              92.246.130.55:
          EOF

      - name: Print inventory file
        run: cat /tmp/inventory.yml