name: Deployment

on:
  workflow_dispatch:
    inputs:
      app_hosts:
        required: true
      load_balancer_host:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create inventory file
        run: |
          APP_HOSTS_BLOCK=""
          IFS=',' read -ra APP_HOSTS <<< "${{ inputs.app_hosts }}"
          for host in "${APP_HOSTS[@]}"; do
            APP_HOSTS_BLOCK+="    $host:\n"
          done

          sed -e "s|{{APP_HOSTS}}|$(printf "$APP_HOSTS_BLOCK")|" \
            main-inventory.tpl > /tmp/inventory.yml

      - name: Print inventory file
        run: cat /tmp/inventory.yml